# Introduction

<center><img src="https://i.imgur.com/9hLRsjZ.jpg" height=400></center>

This dataset was scraped from [nextspaceflight.com](https://nextspaceflight.com/launches/past/?page=1) and includes all the space missions since the beginning of Space Race between the USA and the Soviet Union in 1957!

### Install Package with Country Codes

In [2]:
# If iso3166 is not available in your environment, the notebook also defines
# the country-code mapping needed for this dataset below.
%pip install iso3166

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: iso3166 in C:\Users\manee\AppData\Roaming\Python\Python313\site-packages (3.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

### Upgrade Plotly

Run the cell below if you are working with Google Colab.

In [15]:
%pip install nbformat

Defaulting to user installation because normal site-packages is not writeable
Collecting nbformat
  Downloading nbformat-5.11.1-py3-none-any.whl.metadata (3.7 kB)
Collecting fastjsonschema>=2.15 (from nbformat)
  Downloading fastjsonschema-2.22.2-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: jsonschema>=2.6 in C:\Users\manee\AppData\Roaming\Python\Python313\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\manee\AppData\Roaming\Python\Python313\site-packages (from nbformat) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in C:\Users\manee\AppData\Roaming\Python\Python313\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\manee\AppData\Roaming\Python\Python313\site-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\manee\AppData\Roaming\Python\Python313\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\manee\AppData\Roaming\Python\Python313\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\manee\AppData\Roaming\Python\Python313\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\manee\AppData\Roaming\Python\Python313\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.4.0)
Requirement already satisfied: pywin32>=300 in C:\Users\manee\AppData\Roaming\Python\Python313\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (311)
Downloading nbformat-5.11.1-py3-none-any.whl (79 kB)
Downloading fastjsonschema-2.22.2-py3-none-any.whl (27 kB)
Installing collected packages: fastjsonschema, nbformat

   ---------------------------------------- 0/2 [fastjsonschema]
   ---------------------------------------- 0/2 [fastjsonschema]
   -------------------- ------------------- 1/2 [nbformat]
   -------------------- ------------------- 1/2 [nbformat]
   -------------------- ------------------- 1/2 [nbformat]
   -------------------- ------------------- 1/2 [nbformat]
   -------------------- ------------------- 1/2 [nbformat]
   -------------------- ------------------- 1/2 [nbformat]
   -------------------- ------------------- 1/2 [nbformat]
   -------------------- ------------------- 1/2 [nbformat]
   ---------------------------------------- 2/2 [nbformat]

Successfully installed fastjsonschema-2.22.2 nbformat-5.11.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script jupyter-trust.exe is installed in 'C:\Users\manee\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
%pip install --upgrade plotly

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly in C:\Users\manee\AppData\Roaming\Python\Python313\site-packages (6.5.2)
Collecting plotly
  Downloading plotly-7.0.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\manee\AppData\Roaming\Python\Python313\site-packages (from plotly) (2.17.0)
Requirement already satisfied: packaging in C:\Users\manee\AppData\Roaming\Python\Python313\site-packages (from plotly) (25.0)
Downloading plotly-7.0.0-py3-none-any.whl (9.1 MB)
   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.1 MB 5.2 MB/s eta 0:00:02
   --- ------------------------------------ 0.8/9.1 MB 3.7 MB/s eta 0:00:03
   ----- ---------------------------------- 1.3/9.1 MB 2.3 MB/s eta 0:00:04
   -------- ------------------------------- 1.8/9.1 MB 2.5 MB/s eta 0:00:03
   -------- ------------------------------- 1.8/9.1 MB 2.5 MB/s eta 0:00:03
   ----------- ---------------------------- 2.6/9.1 MB 2.2 MB/s eta 0:00:03
   ------------- -------------------------- 3.1/9.1 MB 2.2 MB/s eta 0:00:03
   --------------- ------------------------ 3.4/9.1 MB 2.2 MB/s eta 0:00:03
   ----------------- ---------------------- 3.9/9.1 MB 2.1 MB/s eta 0:00:03
   ------------------ --------------------- 4.2/9.1 MB 2.1 MB/s eta 0:00:03
   -------------------- ------------------- 4.7/9.1 MB 2.1 MB/s eta 0:00:03
   ---------------------- ----------------- 5.0/9.1 MB 2.0 MB/s eta 0:00:02
   ----------------------- ---------------- 5.2/9.1 MB 2.0 MB/s eta 0:00:02
   ------------------------- -------------- 5.8/9.1 MB 2.0 MB/s eta 0:00:02
   -------------------------- ------------- 6.0/9.1 MB 2.0 MB/s eta 0:00:02
   ---------------------------- ----------- 6.6/9.1 MB 2.0 MB/s eta 0:00:02
   ------------------------------ --------- 6.8/9.1 MB 2.0 MB/s eta 0:00:02
   -------------------------------- ------- 7.3/9.1 MB 2.0 MB/s eta 0:00:01
   ---------------------------------- ----- 7.9/9.1 MB 2.0 MB/s eta 0:00:01
   ------------------------------------- -- 8.4/9.1 MB 2.0 MB/s eta 0:00:01
   -------------------------------------- - 8.7/9.1 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 9.1/9.1 MB 2.0 MB/s  0:00:04
Installing collected packages: plotly
  Attempting uninstall: plotly
    Found existing installation: plotly 6.5.2
    Uninstalling plotly-6.5.2:
      Successfully uninstalled plotly-6.5.2
Successfully installed plotly-7.0.0
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script plotly_get_chrome.exe is installed in 'C:\Users\manee\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

### Import Statements

In [4]:
import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

try:
    from iso3166 import countries
except ImportError:
    countries = None

from datetime import datetime, timedelta
from pathlib import Path

### Notebook Presentation

In [5]:
pd.options.display.float_format = '{:,.2f}'.format

### Load the Data

In [6]:
csv_path = Path('mission_launches.csv')
if not csv_path.exists():
    csv_path = Path('work/mission_launches.csv')

df_data = pd.read_csv(csv_path)
df_data.head()

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA","Fri Aug 07, 2020 05:12 UTC",Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.0,Success
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...","Thu Aug 06, 2020 04:01 UTC",Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA","Tue Aug 04, 2020 23:57 UTC",Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan","Thu Jul 30, 2020 21:25 UTC",Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.0,Success
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA","Thu Jul 30, 2020 11:50 UTC",Atlas V 541 | Perseverance,StatusActive,145.0,Success

# Preliminary Data Exploration

* What is the shape of `df_data`? 
* How many rows and columns does it have?
* What are the column names?
* Are there any NaN values or duplicates?

In [7]:
print(f'The dataset has {df_data.shape[0]:,} rows and {df_data.shape[1]:,} columns.')
df_data.shape

The dataset has 4,324 rows and 9 columns.

(4324, 9)

In [8]:
print('Column names:')
display(df_data.columns.to_frame(index=False, name='column'))

print('\nMissing values by column:')
display(df_data.isna().sum().to_frame('missing_values'))

print(f'\nDuplicate rows: {df_data.duplicated().sum():,}')
display(df_data.sample(5, random_state=42))

Column names:

           column
0    Unnamed: 0.1
1      Unnamed: 0
2    Organisation
3        Location
4            Date
5          Detail
6   Rocket_Status
7           Price
8  Mission_Status

Missing values by column:

                missing_values
Unnamed: 0.1                 0
Unnamed: 0                   0
Organisation                 0
Location                     0
Date                         0
Detail                       0
Rocket_Status                0
Price                     3360
Mission_Status               0

Duplicate rows: 0

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status
2121,2121,2121,NASA,"LC-39A, Kennedy Space Center, Florida, USA","Thu Jul 25, 1985 21:00 UTC",Space Shuttle Challenger | STS-51-F,StatusRetired,450.0,Success
17,17,17,SpaceX,"SLC-40, Cape Canaveral AFS, Florida, USA","Tue Jun 30, 2020 20:10 UTC",Falcon 9 Block 5 | GPS III SV03,StatusActive,50.0,Success
3715,3715,3715,RVSN USSR,"Site 133/3, Plesetsk Cosmodrome, Russia","Tue Nov 21, 1967 14:29 UTC",Cosmos-2I (63SM) | Cosmos 191,StatusRetired,NaN,Success
584,584,584,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA","Mon Nov 18, 2013 18:28 UTC",Atlas V 401 | MAVEN,StatusActive,109.0,Success
4248,4248,4248,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Mon Oct 10, 1960 14:27 UTC",Molniya | 1M n†­1 (Marsnik 1),StatusRetired,NaN,Failure

## Data Cleaning - Check for Missing Values and Duplicates

Consider removing columns containing junk data.

In [ ]:
df_clean = df_data.drop(columns=['Unnamed: 0.1', 'Unnamed: 0']).copy()

df_clean['Price'] = (df_clean['Price'].astype(str).str.replace(',', '', regex=False).replace('nan', np.nan))
df_clean['Price'] = pd.to_numeric(df_clean['Price'], errors='coerce')

df_clean['Date'] = pd.to_datetime(df_clean['Date'], utc=True, errors='coerce', format='mixed')
df_clean['Year'] = df_clean['Date'].dt.year
df_clean['Month_Num'] = df_clean['Date'].dt.month
df_clean['Month'] = df_clean['Date'].dt.month_name()
df_clean['Month_Year'] = df_clean['Date'].dt.to_period('M').dt.to_timestamp()

df_clean['Rocket_Status'] = df_clean['Rocket_Status'].str.replace('Status', '', regex=False)
df_clean.head()

C:\Users\manee\AppData\Local\Temp\ipykernel_20684\2452752150.py:15: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df_clean['Month_Year'] = df_clean['Date'].dt.to_period('M').dt.to_timestamp()

,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,Year,Month_Num,Month,Month_Year
0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,Active,50.00,Success,2020,8,August,2020-08-01
1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,Active,29.75,Success,2020,8,August,2020-08-01
2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,Active,NaN,Success,2020,8,August,2020-08-01
3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,Active,65.00,Success,2020,7,July,2020-07-01
4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,Active,145.00,Success,2020,7,July,2020-07-01

In [10]:
print('Cleaned dataframe info:')
df_clean.info()

print('\nMissing values after cleaning:')
display(df_clean.isna().sum().to_frame('missing_values'))

print(f'\nKnown launch prices: {df_clean["Price"].notna().sum():,} of {len(df_clean):,} rows')
print(f'Duplicate rows after cleaning: {df_clean.duplicated().sum():,}')

Cleaned dataframe info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4324 entries, 0 to 4323
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Organisation    4324 non-null   object
 1   Location        4324 non-null   object
 2   Date            4324 non-null   datetime64[ns, UTC]
 3   Detail          4324 non-null   object
 4   Rocket_Status   4324 non-null   object
 5   Price           964 non-null    float64
 6   Mission_Status  4324 non-null   object
 7   Year            4324 non-null   int32
 8   Month_Num       4324 non-null   int32
 9   Month           4324 non-null   object
 10  Month_Year      4324 non-null   datetime64[ns]
dtypes: datetime64[ns, UTC](1), datetime64[ns](1), float64(1), int32(2), object(6)
memory usage: 337.9+ KB

Missing values after cleaning:

                missing_values
Organisation                 0
Location                     0
Date                         0
Detail                       0
Rocket_Status                0
Price                     3360
Mission_Status               0
Year                         0
Month_Num                    0
Month                        0
Month_Year                   0

Known launch prices: 964 of 4,324 rows
Duplicate rows after cleaning: 1

## Descriptive Statistics

In [11]:
df_clean.describe(include='all')

,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,Year,Month_Num,Month,Month_Year
count,4324,4324,4324,4324,4324,964.00,4324,"4,324.00","4,324.00",4324,4324
unique,56,137,NaN,4278,2,NaN,4,NaN,NaN,12,NaN
top,RVSN USSR,"Site 31/6, Baikonur Cosmodrome, Kazakhstan",NaN,Cosmos-3MRB (65MRB) | BOR-5 Shuttle,Retired,NaN,Success,NaN,NaN,December,NaN
freq,1777,235,NaN,6,3534,NaN,3879,NaN,NaN,450,NaN
mean,NaN,NaN,1987-11-28 17:10:45.735430208+00:00,NaN,NaN,153.79,NaN,"1,987.39",6.75,NaN,1987-11-12 18:51:57.113783488
min,NaN,NaN,1957-10-04 19:28:00+00:00,NaN,NaN,5.30,NaN,"1,957.00",1.00,NaN,1957-10-01 00:00:00
25%,NaN,NaN,1972-04-20 07:28:30+00:00,NaN,NaN,40.00,NaN,"1,972.00",4.00,NaN,1972-04-01 00:00:00
50%,NaN,NaN,1984-12-17 00:17:30+00:00,NaN,NaN,62.00,NaN,"1,984.00",7.00,NaN,1984-12-01 00:00:00
75%,NaN,NaN,2002-09-10 20:50:45+00:00,NaN,NaN,164.00,NaN,"2,002.00",10.00,NaN,2002-09-01 00:00:00
max,NaN,NaN,2020-08-07 05:12:00+00:00,NaN,NaN,"5,000.00",NaN,"2,020.00",12.00,NaN,2020-08-01 00:00:00
std,NaN,NaN,NaN,NaN,NaN,288.45,NaN,18.07,3.42,NaN,NaN

In [12]:
display(df_clean['Organisation'].value_counts().head(20).to_frame('launches'))
display(df_clean['Mission_Status'].value_counts().to_frame('missions'))
display(df_clean['Rocket_Status'].value_counts().to_frame('rockets'))

                  launches
Organisation
RVSN USSR             1777
Arianespace            279
General Dynamics       251
CASC                   251
NASA                   203
VKS RF                 201
US Air Force           161
ULA                    140
Boeing                 136
Martin Marietta        114
SpaceX                 100
MHI                     84
Northrop                83
Lockheed                79
ISRO                    76
Roscosmos               55
ILS                     46
Sea Launch              36
ISAS                    30
Kosmotras               22

                   missions
Mission_Status
Success                3879
Failure                 339
Partial Failure         102
Prelaunch Failure         4

               rockets
Rocket_Status
Retired           3534
Active             790

# Number of Launches per Company

Create a chart that shows the number of space mission launches by organisation.

In [ ]:
launches_by_org = (df_clean['Organisation'].value_counts().rename_axis('Organisation').reset_index(name='Launches'))
launches_by_org.head(20)

        Organisation  Launches
0          RVSN USSR      1777
1        Arianespace       279
2   General Dynamics       251
3               CASC       251
4               NASA       203
5             VKS RF       201
6       US Air Force       161
7                ULA       140
8             Boeing       136
9    Martin Marietta       114
10            SpaceX       100
11               MHI        84
12          Northrop        83
13          Lockheed        79
14              ISRO        76
15         Roscosmos        55
16               ILS        46
17        Sea Launch        36
18              ISAS        30
19         Kosmotras        22

In [23]:
fig = px.bar(
    launches_by_org.head(30),
    x='Launches',
    y='Organisation',
    orientation='h',
    title='Top 30 organisations by number of launches',
    color='Launches',
    color_continuous_scale='viridis',
)
fig.update_layout(yaxis={'categoryorder': 'total ascending'}, height=800)
fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

# Number of Active versus Retired Rockets

How many rockets are active compared to those that are decomissioned?

In [ ]:
rocket_status = (df_clean['Rocket_Status'].value_counts().rename_axis('Rocket_Status').reset_index(name='Count'))
rocket_status

  Rocket_Status  Count
0       Retired   3534
1        Active    790

In [ ]:
fig = px.pie(
    rocket_status,
    names='Rocket_Status',
    values='Count',
    title='Active vs retired rockets',
    hole=0.35,
)
fig.show()

# Distribution of Mission Status

How many missions were successful?
How many missions failed?

In [ ]:
mission_status = (df_clean['Mission_Status'].value_counts().rename_axis('Mission_Status').reset_index(name='Count'))
mission_status

      Mission_Status  Count
0            Success   3879
1            Failure    339
2    Partial Failure    102
3  Prelaunch Failure      4

In [ ]:
fig = px.bar(
    mission_status,
    x='Mission_Status',
    y='Count',
    color='Mission_Status',
    title='Distribution of mission status',
    text='Count',
)
fig.update_traces(textposition='outside')
fig.show()

# How Expensive are the Launches? 

Create a histogram and visualise the distribution. The price column is given in USD millions (careful of missing values).

In [ ]:
known_prices = df_clean.dropna(subset=['Price']).copy()
known_prices[['Organisation', 'Date', 'Detail', 'Price']].sort_values('Price', ascending=False).head(10)

     Organisation                      Date                                  Detail    Price
1916    RVSN USSR 1988-11-15 03:00:00+00:00                  Energiya/Buran | Buran 5,000.00
2000    RVSN USSR 1987-05-15 17:30:00+00:00  Energiya/Polyus | Polyus Space Station 5,000.00
3475         NASA 1970-04-11 19:13:00+00:00                    Saturn V | Apollo 13 1,160.00
3683         NASA 1968-04-04 12:00:00+00:00                     Saturn V | Apollo 6 1,160.00
3243         NASA 1972-04-16 17:54:00+00:00                    Saturn V | Apollo 16 1,160.00
3384         NASA 1971-01-31 21:03:00+00:00                    Saturn V | Apollo 14 1,160.00
3603         NASA 1968-12-21 12:51:00+00:00                     Saturn V | Apollo 8 1,160.00
3511         NASA 1969-11-14 16:22:00+00:00                    Saturn V | Apollo 12 1,160.00
3545         NASA 1969-07-16 13:32:00+00:00                    Saturn V | Apollo 11 1,160.00
3584         NASA 1969-03-03 16:00:00+00:00                     Saturn V | Apollo 9 1,160.00

In [ ]:
fig = px.histogram(
    known_prices,
    x='Price',
    nbins=60,
    marginal='box',
    title='Distribution of launch prices with known costs',
    labels={'Price': 'Launch price (USD millions)'},
)
fig.update_layout(bargap=0.05)
fig.show()

# Use a Choropleth Map to Show the Number of Launches by Country

* Create a choropleth map using [the plotly documentation](https://plotly.com/python/choropleth-maps/)
* Experiment with [plotly's available colours](https://plotly.com/python/builtin-colorscales/). I quite like the sequential colour `matter` on this map. 
* You'll need to extract a `country` feature as well as change the country names that no longer exist.

Wrangle the Country Names

You'll need to use a 3 letter country code for each country. You might have to change some country names.

* Russia is the Russian Federation
* New Mexico should be USA
* Yellow Sea refers to China
* Shahrud Missile Test Site should be Iran
* Pacific Missile Range Facility should be USA
* Barents Sea should be Russian Federation
* Gran Canaria should be USA


You can use the iso3166 package to convert the country names to Alpha3 format.

In [ ]:
country_replacements = {
    'Russia': 'Russian Federation',
    'New Mexico': 'USA',
    'Yellow Sea': 'China',
    'Shahrud Missile Test Site': 'Iran',
    'Pacific Missile Range Facility': 'USA',
    'Barents Sea': 'Russian Federation',
    'Gran Canaria': 'USA',
}

alpha3_lookup = {
    'Australia': 'AUS',
    'Brazil': 'BRA',
    'China': 'CHN',
    'France': 'FRA',
    'India': 'IND',
    'Iran': 'IRN',
    'Israel': 'ISR',
    'Japan': 'JPN',
    'Kazakhstan': 'KAZ',
    'Kenya': 'KEN',
    'New Zealand': 'NZL',
    'North Korea': 'PRK',
    'Pacific Ocean': 'PCE',
    'Russian Federation': 'RUS',
    'South Korea': 'KOR',
    'USA': 'USA',
}

def country_to_alpha3(country_name):
    if country_name in alpha3_lookup:
        return alpha3_lookup[country_name]
    if countries is not None:
        try:
            return countries.get(country_name).alpha3
        except KeyError:
            return np.nan
    return np.nan

df_clean['Country'] = df_clean['Location'].str.split(',').str[-1].str.strip()
df_clean['Country'] = df_clean['Country'].replace(country_replacements)
df_clean['Country_Code'] = df_clean['Country'].apply(country_to_alpha3)

df_clean[['Location', 'Country', 'Country_Code']].drop_duplicates().head(20)

                                                     Location             Country Country_Code
0                  LC-39A, Kennedy Space Center, Florida, USA                 USA          USA
1   Site 9401 (SLS-2), Jiuquan Satellite Launch Center, China               China          CHN
2                               Pad A, Boca Chica, Texas, USA                 USA          USA
3                Site 200/39, Baikonur Cosmodrome, Kazakhstan          Kazakhstan          KAZ
4                    SLC-41, Cape Canaveral AFS, Florida, USA                 USA          USA
5                LC-9, Taiyuan Satellite Launch Center, China               China          CHN
6                  Site 31/6, Baikonur Cosmodrome, Kazakhstan          Kazakhstan          KAZ
7             LC-101, Wenchang Satellite Launch Center, China               China          CHN
8                    SLC-40, Cape Canaveral AFS, Florida, USA                 USA          USA
9                      LA-Y1, Tanegashima Space Center, Japan               Japan          JPN
10              LP-0B, Wallops Flight Facility, Virginia, USA                 USA          USA
11            Site 95, Jiuquan Satellite Launch Center, China               China          CHN
12               LC-3, Xichang Satellite Launch Center, China               China          CHN
13                           Pad 1, Palmachim Airbase, Israel              Israel          ISR
15            Rocket Lab LC-1A, M?hia Peninsula, New Zealand         New Zealand          NZL
18               LC-2, Xichang Satellite Launch Center, China               China          CHN
26                     Xichang Satellite Launch Center, China               China          CHN
27    Cosmic Girl, Mojave Air and Space Port, California, USA                 USA          USA
28                     Site 43/4, Plesetsk Cosmodrome, Russia  Russian Federation          RUS
29                     LA-Y2, Tanegashima Space Center, Japan               Japan          JPN

In [ ]:
launches_by_country = (df_clean.groupby(['Country', 'Country_Code'], dropna=False).size().reset_index(name='Launches').sort_values('Launches', ascending=False))
display(launches_by_country)

fig = px.choropleth(
    launches_by_country[launches_by_country['Country_Code'] != 'PCE'],
    locations='Country_Code',
    color='Launches',
    hover_name='Country',
    color_continuous_scale='matter',
    title='Number of launches by country',
)
fig.show()

               Country Country_Code  Launches
13  Russian Federation          RUS      1398
15                 USA          USA      1351
8           Kazakhstan          KAZ       701
3               France          FRA       303
2                China          CHN       269
7                Japan          JPN       126
4                India          IND        76
12       Pacific Ocean          PCE        36
5                 Iran          IRN        14
10         New Zealand          NZL        13
6               Israel          ISR        11
9                Kenya          KEN         9
0            Australia          AUS         6
11         North Korea          PRK         5
1               Brazil          BRA         3
14         South Korea          KOR         3

# Use a Choropleth Map to Show the Number of Failures by Country

In [ ]:
failures = df_clean[df_clean['Mission_Status'].str.contains('Failure', case=False, na=False)]
failures_by_country = (
    failures.groupby(['Country', 'Country_Code'], dropna=False)
    .size()
    .reset_index(name='Failures')
    .sort_values('Failures', ascending=False)
)
failures_by_country

               Country Country_Code  Failures
14                 USA          USA       163
8           Kazakhstan          KAZ        93
12  Russian Federation          RUS        93
2                China          CHN        25
3               France          FRA        18
7                Japan          JPN        13
4                India          IND        13
5                 Iran          IRN         9
11       Pacific Ocean          PCE         3
0            Australia          AUS         3
1               Brazil          BRA         3
10         North Korea          PRK         3
6               Israel          ISR         2
9          New Zealand          NZL         2
13         South Korea          KOR         2

In [ ]:
fig = px.choropleth(
    failures_by_country[failures_by_country['Country_Code'] != 'PCE'],
    locations='Country_Code',
    color='Failures',
    hover_name='Country',
    color_continuous_scale='Reds',
    title='Number of mission failures by country',
)
fig.show()

# Create a Plotly Sunburst Chart of the countries, organisations, and mission status.

In [ ]:
sunburst_data = (
    df_clean.groupby(['Country', 'Organisation', 'Mission_Status'], dropna=False)
    .size()
    .reset_index(name='Launches')
)
sunburst_data.head()

     Country Organisation Mission_Status  Launches
0  Australia         AMBA        Success         1
1  Australia       CECLES        Failure         2
2  Australia       CECLES        Success         1
3  Australia          RAE        Failure         1
4  Australia          RAE        Success         1

In [ ]:
fig = px.sunburst(
    sunburst_data,
    path=['Country', 'Organisation', 'Mission_Status'],
    values='Launches',
    title='Launches by country, organisation, and mission status',
    color='Mission_Status',
)
fig.update_layout(height=850)
fig.show()

In [ ]:
sunburst_data.sort_values('Launches', ascending=False).head(15)

                Country      Organisation Mission_Status  Launches
81   Russian Federation         RVSN USSR        Success      1119
58           Kazakhstan         RVSN USSR        Success       495
19               France       Arianespace        Success       267
9                 China              CASC        Success       231
105                 USA  General Dynamics        Success       203
114                 USA              NASA        Success       186
88   Russian Federation            VKS RF        Success       147
124                 USA               ULA        Success       139
98                  USA            Boeing        Success       131
127                 USA      US Air Force        Success       129
111                 USA   Martin Marietta        Success       100
122                 USA            SpaceX        Success        94
44                Japan               MHI        Success        80
117                 USA          Northrop        Success        74
108                 USA          Lockheed        Success        74

# Analyse the Total Amount of Money Spent by Organisation on Space Missions

In [ ]:
spend_by_org = (
    known_prices.groupby('Organisation', as_index=False)
    .agg(Total_Spent=('Price', 'sum'), Known_Prices=('Price', 'count'))
    .sort_values('Total_Spent', ascending=False)
)
spend_by_org.head(20)

       Organisation  Total_Spent  Known_Prices
14             NASA    76,280.00           149
0       Arianespace    16,345.00            96
21              ULA    14,798.00            98
16        RVSN USSR    10,000.00             2
2              CASC     6,340.26           158
20           SpaceX     5,444.00            99
15         Northrop     3,930.00            83
12              MHI     3,532.50            37
8              ISRO     2,177.00            67
22     US Air Force     1,550.92            26
23           VKS RF     1,548.90            33
7               ILS     1,320.00            13
1            Boeing     1,241.00             7
18        Roscosmos     1,187.50            23
13  Martin Marietta       721.40             9
10        Kosmotras       638.00            22
5          Eurockot       543.40            13
11         Lockheed       280.00             8
9              JAXA       168.00             3
17       Rocket Lab        97.50            13

In [ ]:
fig = px.bar(
    spend_by_org.head(20),
    x='Total_Spent',
    y='Organisation',
    orientation='h',
    color='Total_Spent',
    color_continuous_scale='plasma',
    title='Total known launch spending by organisation',
    labels={'Total_Spent': 'Total known spending (USD millions)'},
    hover_data=['Known_Prices'],
)
fig.update_layout(yaxis={'categoryorder': 'total ascending'}, height=700)
fig.show()

In [ ]:
print('NASA, Arianespace, and ULA account for the largest known spending totals in this dataset.')
print('This view only includes launches with a listed price, so totals understate true lifetime spending.')

NASA, Arianespace, and ULA account for the largest known spending totals in this dataset.
This view only includes launches with a listed price, so totals understate true lifetime spending.

# Analyse the Amount of Money Spent by Organisation per Launch

In [ ]:
avg_spend_by_org = (
    known_prices.groupby('Organisation', as_index=False)
    .agg(Average_Price=('Price', 'mean'), Median_Price=('Price', 'median'), Known_Prices=('Price', 'count'))
    .query('Known_Prices >= 3')
    .sort_values('Average_Price', ascending=False)
)
avg_spend_by_org.head(20)

       Organisation  Average_Price  Median_Price  Known_Prices
14             NASA         511.95        450.00           149
1            Boeing         177.29        164.00             7
0       Arianespace         170.26        200.00            96
21              ULA         151.00        123.00            98
7               ILS         101.54        109.00            13
12              MHI          95.47         90.00            37
13  Martin Marietta          80.16         35.00             9
22     US Air Force          59.65         59.00            26
9              JAXA          56.00         39.00             3
20           SpaceX          54.99         56.50            99
18        Roscosmos          51.63         48.50            23
15         Northrop          47.35         40.00            83
23           VKS RF          46.94         41.80            33
5          Eurockot          41.80         41.80            13
2              CASC          40.13         30.80           158
11         Lockheed          35.00         35.00             8
8              ISRO          32.49         31.00            67
10        Kosmotras          29.00         29.00            22
17       Rocket Lab           7.50          7.50            13

In [ ]:
fig = px.bar(
    avg_spend_by_org.head(20),
    x='Average_Price',
    y='Organisation',
    orientation='h',
    color='Average_Price',
    color_continuous_scale='cividis',
    title='Average launch price by organisation',
    labels={'Average_Price': 'Average known price per launch (USD millions)'},
    hover_data=['Median_Price', 'Known_Prices'],
)
fig.update_layout(yaxis={'categoryorder': 'total ascending'}, height=700)
fig.show()

In [ ]:
display(avg_spend_by_org.tail(10).sort_values('Average_Price'))
print('Average price comparisons are limited to organisations with at least three known prices.')

Average price comparisons are limited to organisations with at least three known prices.

   Organisation  Average_Price  Median_Price  Known_Prices
17   Rocket Lab           7.50          7.50            13
10    Kosmotras          29.00         29.00            22
8          ISRO          32.49         31.00            67
11     Lockheed          35.00         35.00             8
2          CASC          40.13         30.80           158
5      Eurockot          41.80         41.80            13
23       VKS RF          46.94         41.80            33
15     Northrop          47.35         40.00            83
18    Roscosmos          51.63         48.50            23
20       SpaceX          54.99         56.50            99

# Chart the Number of Launches per Year

In [ ]:
launches_per_year = (
    df_clean.groupby('Year')
    .size()
    .reset_index(name='Launches')
    .sort_values('Year')
)
launches_per_year.tail()

    Year  Launches
59  2016        90
60  2017        92
61  2018       117
62  2019       109
63  2020        63

In [ ]:
fig = px.line(
    launches_per_year,
    x='Year',
    y='Launches',
    markers=True,
    title='Number of launches per year',
)
fig.show()

# Chart the Number of Launches Month-on-Month until the Present

Which month has seen the highest number of launches in all time? Superimpose a rolling average on the month on month time series chart.

In [ ]:
launches_monthly = (
    df_clean.set_index('Date')
    .resample('MS')
    .size()
    .rename('Launches')
    .reset_index()
)
launches_monthly['Rolling_12M_Avg'] = launches_monthly['Launches'].rolling(12, min_periods=1).mean()
launches_monthly.sort_values('Launches', ascending=False).head(10)

                         Date  Launches  Rolling_12M_Avg
170 1971-12-01 00:00:00+00:00        18             9.92
126 1968-04-01 00:00:00+00:00        16             9.00
215 1975-09-01 00:00:00+00:00        16             9.58
746 2019-12-01 00:00:00+00:00        16             9.08
239 1977-09-01 00:00:00+00:00        16            10.00
734 2018-12-01 00:00:00+00:00        15             9.75
156 1970-10-01 00:00:00+00:00        15             8.42
210 1975-04-01 00:00:00+00:00        15             8.92
225 1976-07-01 00:00:00+00:00        15             9.50
163 1971-05-01 00:00:00+00:00        14            10.33

In [ ]:
fig = px.line(
    launches_monthly,
    x='Date',
    y=['Launches', 'Rolling_12M_Avg'],
    title='Monthly launches with 12-month rolling average',
    labels={'value': 'Launches', 'variable': 'Series'},
)
fig.show()

# Launches per Month: Which months are most popular and least popular for launches?

Some months have better weather than others. Which time of year seems to be best for space missions?

In [ ]:
month_order = ['January', 'February', 'March', 'April', 'May', 'June',
               'July', 'August', 'September', 'October', 'November', 'December']
launches_by_month = (
    df_clean.groupby(['Month_Num', 'Month'])
    .size()
    .reset_index(name='Launches')
    .sort_values('Month_Num')
)
launches_by_month

    Month_Num      Month  Launches
0           1    January       268
1           2   February       336
2           3      March       353
3           4      April       383
4           5        May       326
5           6       June       402
6           7       July       351
7           8     August       373
8           9  September       365
9          10    October       381
10         11   November       336
11         12   December       450

In [ ]:
fig = px.bar(
    launches_by_month,
    x='Month',
    y='Launches',
    category_orders={'Month': month_order},
    color='Launches',
    color_continuous_scale='teal',
    title='Launches by calendar month',
)
fig.show()

most_popular = launches_by_month.loc[launches_by_month['Launches'].idxmax()]
least_popular = launches_by_month.loc[launches_by_month['Launches'].idxmin()]
print(f"Most popular month: {most_popular['Month']} ({most_popular['Launches']:,} launches)")
print(f"Least popular month: {least_popular['Month']} ({least_popular['Launches']:,} launches)")

Most popular month: December (450 launches)
Least popular month: January (268 launches)

# How has the Launch Price varied Over Time? 

Create a line chart that shows the average price of rocket launches over time.

In [ ]:
avg_price_year = (
    known_prices.groupby('Year')
    .agg(Average_Price=('Price', 'mean'), Median_Price=('Price', 'median'), Known_Prices=('Price', 'count'))
    .reset_index()
)
avg_price_year.tail()

    Year  Average_Price  Median_Price  Known_Prices
45  2016          79.46         62.00            64
46  2017          69.49         62.00            66
47  2018          64.75         50.00            88
48  2019          59.61         48.50            73
49  2020          56.65         49.25            52

In [ ]:
fig = px.line(
    avg_price_year,
    x='Year',
    y='Average_Price',
    markers=True,
    title='Average known launch price over time',
    labels={'Average_Price': 'Average launch price (USD millions)'},
    hover_data=['Median_Price', 'Known_Prices'],
)
fig.show()

# Chart the Number of Launches over Time by the Top 10 Organisations. 

How has the dominance of launches changed over time between the different players?

In [ ]:
top_10_orgs = launches_by_org.head(10)['Organisation'].tolist()
top_orgs_by_year = (
    df_clean[df_clean['Organisation'].isin(top_10_orgs)]
    .groupby(['Year', 'Organisation'])
    .size()
    .reset_index(name='Launches')
)
top_orgs_by_year.head()

   Year      Organisation  Launches
0  1957         RVSN USSR         2
1  1958              NASA         2
2  1958         RVSN USSR         5
3  1958      US Air Force         2
4  1959  General Dynamics         1

In [ ]:
fig = px.line(
    top_orgs_by_year,
    x='Year',
    y='Launches',
    color='Organisation',
    markers=True,
    title='Launches over time by the top 10 organisations',
)
fig.show()

In [ ]:
print('The USSR-era state programme dominated much of the early dataset, while CASC, SpaceX, and Roscosmos become prominent later.')

The USSR-era state programme dominated much of the early dataset, while CASC, SpaceX, and Roscosmos become prominent later.

# Cold War Space Race: USA vs USSR

The cold war lasted from the start of the dataset up until 1991.

In [ ]:
cold_war = df_clean[df_clean['Year'].between(1957, 1991)].copy()
cold_war['Superpower'] = np.select(
    [
        cold_war['Country'].eq('USA'),
        cold_war['Country'].isin(['Russian Federation', 'Kazakhstan']),
    ],
    ['USA', 'USSR'],
    default='Other',
)
cold_war_superpowers = cold_war[cold_war['Superpower'].isin(['USA', 'USSR'])].copy()
cold_war_superpowers[['Date', 'Country', 'Organisation', 'Mission_Status', 'Superpower']].head()

                          Date             Country      Organisation Mission_Status Superpower
1718 1991-12-20 00:00:00+00:00          Kazakhstan         RVSN USSR        Success       USSR
1719 1991-12-18 03:54:00+00:00  Russian Federation          Yuzhmash        Success       USSR
1721 1991-12-07 22:47:00+00:00                 USA  General Dynamics        Success        USA
1722 1991-11-28 13:23:00+00:00                 USA  General Dynamics        Success        USA
1723 1991-11-27 03:30:00+00:00  Russian Federation         RVSN USSR        Success       USSR

In [ ]:
cold_war_summary = (
    cold_war_superpowers.groupby('Superpower')
    .agg(Launches=('Mission_Status', 'size'), Failures=('Mission_Status', lambda s: s.str.contains('Failure').sum()))
)
cold_war_summary['Failure_Rate'] = cold_war_summary['Failures'] / cold_war_summary['Launches']
cold_war_summary

            Launches  Failures  Failure_Rate
Superpower
USA              662       126          0.19
USSR            1770       162          0.09

## Create a Plotly Pie Chart comparing the total number of launches of the USSR and the USA

Hint: Remember to include former Soviet Republics like Kazakhstan when analysing the total number of launches.

In [ ]:
cold_war_launches = (
    cold_war_superpowers['Superpower']
    .value_counts()
    .rename_axis('Superpower')
    .reset_index(name='Launches')
)
cold_war_launches

  Superpower  Launches
0       USSR      1770
1        USA       662

In [ ]:
fig = px.pie(
    cold_war_launches,
    names='Superpower',
    values='Launches',
    title='Cold War launches: USA vs USSR',
    hole=0.35,
)
fig.show()

## Create a Chart that Shows the Total Number of Launches Year-On-Year by the Two Superpowers

In [ ]:
cold_war_yearly = (
    cold_war_superpowers.groupby(['Year', 'Superpower'])
    .size()
    .reset_index(name='Launches')
)
cold_war_yearly.head()

   Year Superpower  Launches
0  1957        USA         1
1  1957       USSR         2
2  1958        USA        23
3  1958       USSR         5
4  1959        USA        16

In [ ]:
fig = px.line(
    cold_war_yearly,
    x='Year',
    y='Launches',
    color='Superpower',
    markers=True,
    title='Cold War launches by year: USA vs USSR',
)
fig.show()

## Chart the Total Number of Mission Failures Year on Year.

In [ ]:
cold_war_failures_yearly = (
    cold_war_superpowers[cold_war_superpowers['Mission_Status'].str.contains('Failure', case=False, na=False)]
    .groupby(['Year', 'Superpower'])
    .size()
    .reset_index(name='Failures')
)
cold_war_failures_yearly.head()

   Year Superpower  Failures
0  1957        USA         1
1  1958        USA        18
2  1958       USSR         4
3  1959        USA        10
4  1959       USSR         2

In [ ]:
fig = px.line(
    cold_war_failures_yearly,
    x='Year',
    y='Failures',
    color='Superpower',
    markers=True,
    title='Cold War mission failures by year',
)
fig.show()

## Chart the Percentage of Failures over Time

Did failures go up or down over time? Did the countries get better at minimising risk and improving their chances of success over time?

In [ ]:
cold_war_status_yearly = (
    cold_war_superpowers.assign(Is_Failure=cold_war_superpowers['Mission_Status'].str.contains('Failure', case=False, na=False))
    .groupby(['Year', 'Superpower'])
    .agg(Launches=('Is_Failure', 'size'), Failures=('Is_Failure', 'sum'))
    .reset_index()
)
cold_war_status_yearly['Failure_Rate'] = cold_war_status_yearly['Failures'] / cold_war_status_yearly['Launches']
cold_war_status_yearly.head()

   Year Superpower  Launches  Failures  Failure_Rate
0  1957        USA         1         1          1.00
1  1957       USSR         2         0          0.00
2  1958        USA        23        18          0.78
3  1958       USSR         5         4          0.80
4  1959        USA        16        10          0.62

In [ ]:
fig = px.line(
    cold_war_status_yearly,
    x='Year',
    y='Failure_Rate',
    color='Superpower',
    markers=True,
    title='Cold War failure percentage over time',
    labels={'Failure_Rate': 'Failure rate'},
)
fig.update_yaxes(tickformat='.0%')
fig.show()

In [ ]:
early = cold_war_status_yearly[cold_war_status_yearly['Year'].between(1957, 1966)].groupby('Superpower')['Failure_Rate'].mean()
late = cold_war_status_yearly[cold_war_status_yearly['Year'].between(1982, 1991)].groupby('Superpower')['Failure_Rate'].mean()
comparison = pd.DataFrame({'1957-1966 average': early, '1982-1991 average': late})
comparison['Change'] = comparison['1982-1991 average'] - comparison['1957-1966 average']
display(comparison)
print('Failure rates generally fell from the first decade of the Space Race to the final decade of the Cold War.')

Failure rates generally fell from the first decade of the Space Race to the final decade of the Cold War.

            1957-1966 average  1982-1991 average  Change
Superpower
USA                      0.42               0.09   -0.33
USSR                     0.36               0.04   -0.31

# For Every Year Show which Country was in the Lead in terms of Total Number of Launches up to and including including 2020)

Do the results change if we only look at the number of successful launches?

In [ ]:
country_year = (
    df_clean.groupby(['Year', 'Country'])
    .size()
    .reset_index(name='Launches')
)
country_year['Rank'] = country_year.groupby('Year')['Launches'].rank(method='first', ascending=False)
country_leaders = country_year[country_year['Rank'].eq(1)].sort_values('Year')
country_leaders[['Year', 'Country', 'Launches']].tail(15)

     Year Country  Launches
302  2006     USA        18
311  2007     USA        19
320  2008     USA        15
330  2009     USA        25
338  2010     USA        15
347  2011     USA        18
356  2012     USA        13
365  2013     USA        19
374  2014     USA        23
382  2015     USA        22
391  2016     USA        27
400  2017     USA        30
401  2018   China        39
409  2019   China        34
418  2020   China        22

In [ ]:
successful_country_year = (
    df_clean[df_clean['Mission_Status'].eq('Success')]
    .groupby(['Year', 'Country'])
    .size()
    .reset_index(name='Successful_Launches')
)
successful_country_year['Rank'] = successful_country_year.groupby('Year')['Successful_Launches'].rank(method='first', ascending=False)
successful_country_leaders = successful_country_year[successful_country_year['Rank'].eq(1)].sort_values('Year')

comparison_leaders = country_leaders[['Year', 'Country', 'Launches']].merge(
    successful_country_leaders[['Year', 'Country', 'Successful_Launches']],
    on='Year',
    suffixes=('_All_Launches_Leader', '_Successful_Launches_Leader'),
)
comparison_leaders.tail(20)

    Year Country_All_Launches_Leader  Launches Country_Successful_Launches_Leader  Successful_Launches
44  2001                         USA        22                                USA                   21
45  2002                         USA        17                                USA                   17
46  2003                         USA        23                                USA                   22
47  2004                         USA        16                                USA                   15
48  2005                         USA        12                                USA                   12
49  2006                         USA        18                                USA                   17
50  2007                         USA        19                                USA                   17
51  2008                         USA        15                                USA                   14
52  2009                         USA        25                                USA                   24
53  2010                         USA        15                                USA                   15
54  2011                         USA        18                                USA                   17
55  2012                         USA        13                                USA                   12
56  2013                         USA        19                                USA                   19
57  2014                         USA        23                                USA                   22
58  2015                         USA        22                                USA                   20
59  2016                         USA        27                                USA                   26
60  2017                         USA        30                                USA                   30
61  2018                       China        39                              China                   38
62  2019                       China        34                              China                   32
63  2020                       China        22                                USA                   20

# Create a Year-on-Year Chart Showing the Organisation Doing the Most Number of Launches

Which organisation was dominant in the 1970s and 1980s? Which organisation was dominant in 2018, 2019 and 2020?

In [ ]:
org_year = (
    df_clean.groupby(['Year', 'Organisation'])
    .size()
    .reset_index(name='Launches')
)
org_year['Rank'] = org_year.groupby('Year')['Launches'].rank(method='first', ascending=False)
org_leaders = org_year[org_year['Rank'].eq(1)].sort_values('Year')
org_leaders.tail(20)

     Year Organisation  Launches  Rank
379  2001  Arianespace         8  1.00
391  2002  Arianespace        12  1.00
408  2003       Boeing         9  1.00
423  2004       Boeing         8  1.00
433  2005  Arianespace         5  1.00
449  2006       Boeing         8  1.00
475  2007          ULA        13  1.00
478  2008         CASC         9  1.00
503  2009          ULA        16  1.00
516  2010          ULA         8  1.00
529  2011          ULA        11  1.00
541  2012          ULA        10  1.00
555  2013          ULA        11  1.00
567  2014          ULA        14  1.00
569  2015  Arianespace        12  1.00
583  2016         CASC        22  1.00
611  2017       SpaceX        18  1.00
616  2018         CASC        37  1.00
632  2019         CASC        27  1.00
649  2020         CASC        19  1.00

In [ ]:
fig = px.bar(
    org_leaders,
    x='Year',
    y='Launches',
    color='Organisation',
    title='Organisation with the most launches each year',
    hover_data=['Organisation'],
)
fig.show()

In [ ]:
dominant_70s_80s = org_leaders[org_leaders['Year'].between(1970, 1989)]['Organisation'].value_counts()
recent_dominant = org_leaders[org_leaders['Year'].isin([2018, 2019, 2020])][['Year', 'Organisation', 'Launches']]

print('Dominant organisations in the 1970s and 1980s:')
display(dominant_70s_80s)

print('\nDominant organisations in 2018, 2019, and 2020:')
display(recent_dominant)

Dominant organisations in the 1970s and 1980s:

Dominant organisations in 2018, 2019, and 2020:

Organisation
RVSN USSR    20

     Year Organisation  Launches
616  2018         CASC        37
632  2019         CASC        27
649  2020         CASC        19